import type { LibraryDef } from "../types.js";

namespace EasyLife {
  export const V1_09 = {
    name: 'EasyLife',
    version: 'V1_09',
    md5: 'c6a1d9f26d6900ce65dd5097b769bc63',
    type: 'pro',
    same: {
      Ellchg: 'Ellset',
      StSetStr_IIS: 'StSet_III',
      StSetStr_IIIS: 'StSet_IIII',
      StSetStr_IIIIS: 'StSet_IIIII',
      StSetStr_IIIIIS: 'StSet_IIIIII',
    },
    routines: {
      ElbankName: 65,
      ElBase: 117,
      ElbnkHere: 158,
      ElcloseFont: 161,
      ElcloseFonts: 163,
      Elcompiled: 149,
      Elexec: 143,
      Elexists: 105,
      Elextb: 78,
      Elextw: 79,
      ElfAsc_SI: 18,
      ElfAsc_SII: 19,
      ElfChar_SS: 26,
      ElfChar_SSI: 27,
      ElfControl_S: 44,
      ElfControl_SI: 45,
      ElfFailEnd: 152,
      ElfFailStart: 151,
      ElfLastAsc_SI: 22,
      ElfLastAsc_SII: 23,
      ElfLastChar_SS: 30,
      ElfLastChar_SSI: 31,
      ElfLastNotAsc_SI: 24,
      ElfLastNotAsc_SII: 25,
      ElfLastNotChar_SS: 32,
      ElfLastNotChar_SSI: 33,
      ElfNotAsc_SI: 20,
      ElfNotAsc_SII: 21,
      ElfNotChar_SS: 28,
      ElfNotChar_SSI: 29,
      ElfNthAsc: 53,
      ElfNthChar: 52,
      ElfNumAsc: 51,
      ElfNumChar: 50,
      EliconifyAmos: 123,
      EliconifyBegin: 124,
      EliconifyEnd: 126,
      EliconifyTest: 125,
      Elin: 129,
      ElinExists: 127,
      ElinGet: 128,
      ElLapex: 156,
      ElLapey: 157,
      ElLapsx: 154,
      ElLapsy: 155,
      Ellchg: 77,
      Ellclr: 75,
      Ellong_I__S: 46,
      Ellong_S__I: 47,
      Ellset: 73,
      Elltst: 71,
      Elmem_II__S: 67,
      Elmem_III__S: 68,
      Elmem_IS__V: 69,
      ElmemInc: 111,
      Elmessage: 64,
      ElmessageExists: 147,
      ElmzErase: 92,
      Elmznex: 90,
      Elmzney: 91,
      Elmznsx: 88,
      Elmznsy: 89,
      Elmzone_III: 95,
      Elmzone_II: 94,
      Elmzoneg: 93,
      Elmzonen: 96,
      ElmzReserve: 80,
      ElmzSet_IIIIII: 85,
      ElmzSet_II: 86,
      ElopenFont: 160,
      Elout: 122,
      EloutExists: 121,
      ElOverlap: 153,
      ElpadAsc: 145,
      ElpadChar: 144,
      ElpatCase: 133,
      ElpatDef: 135,
      ElpatEscape: 142,
      ElpatFree: 139,
      ElpatNocase: 134,
      ElpatRemove: 141,
      ElpatSetCase: 137,
      ElpatSetNocase: 138,
      ElpatTest: 140,
      ElppAllocate: 63,
      ElppBuf: 56,
      ElppCrunch: 59,
      ElppFree: 58,
      ElppKeepOff: 61,
      ElppKeepOn: 60,
      ElppLen: 57,
      ElppLoad: 55,
      Elpro: 148,
      Elprotect: 109,
      ElrasterWait: 107,
      Elreset: 108,
      ElsBankName: 66,
      ElsetFont: 162,
      ElsProtect: 110,
      Eltest_get_II__I: 256,
      Eltest_set_III: 255,
      ElwbClose: 119,
      ElwbOpen: 118,
      ElwbTest: 120,
      Elwchg: 76,
      Elwclr: 74,
      Elword_I__S: 48,
      Elword_S__I: 49,
      Elwset: 72,
      Elwtst: 70,
      ElxpkBload_SSI: 175,
      ElxpkBload_SI: 174,
      ElxpkBsave_IISSS: 181,
      ElxpkBsave_IISS: 182,
      ElxpkError: 177,
      ElxpkLoad_S: 170,
      ElxpkLoad_SI: 171,
      ElxpkLoad_SS: 172,
      ElxpkLoad_SSI: 173,
      ElxpkLof: 185,
      ElxpkSave_ISSS: 178,
      ElxpkSave_ISS: 179,
      ElzbAdd: 100,
      ElzbMultiAdd_II: 102,
      ElzbMultiAdd_I: 103,
      Elznex_I: 11,
      Elznex_II: 12,
      Elzney_I: 13,
      Elzney_II: 14,
      ElznShift_III: 15,
      ElznShift_IIIII: 16,
      Elznsx_I: 7,
      Elznsx_II: 8,
      Elznsy_I: 9,
      Elznsy_II: 10,
      MuiAdd: 236,
      MuiApp: 221,
      MuiApplication: 220,
      MuiBegin: 217,
      MuiDispose: 222,
      MuiDo: 213,
      MuiFlush: 227,
      //MuiFn: 213, /* alias for MuiDo */
      MuiGet_IS__S: 209,
      MuiGet_II__S: 210,
      MuiGet_IS__I: 207,
      MuiGet_II__I: 208,
      MuiHook: 228,
      MuiInput: 225,
      MuiMakeButton: 223,
      MuiMakePopbutton: 224,
      MuiNew_SS: 219,
      MuiNew_S: 218,
      MuiNotify_ISIIS: 214,
      MuiNotify_IIIIS: 215,
      MuiRemove: 237,
      MuiRequest_ISSSS: 230,
      MuiRequest_ISSS: 229,
      MuiSet_ISI: 205,
      MuiSet_III: 206,
      MuiSetStr_ISS: 211,
      MuiSetStr_IIS: 212,
      StCmp_IIS: 286,
      StCmp_IIIS: 287,
      StCmp_IIIIS: 288,
      StCmp_IIIIIS: 289,
      StCopy: 268,
      StDup: 267,
      StErase: 291,
      StFree: 262,
      StFreeAll: 266,
      StGet_II__S: 277,
      StGet_III__S: 278,
      StGet_IIII__S: 279,
      StGet_IIIII__S: 280,
      StGet_II__I: 273,
      StGet_III__I: 274,
      StGet_IIII__I: 275,
      StGet_IIIII__I: 276,
      StInput: 269,
      StLen: 272,
      StLoad: 264,
      StLookup: 290,
      StNew: 263,
      StOutput: 270,
      StSave: 265,
      StSet_III: 281,
      StSet_IIII: 282,
      StSet_IIIII: 283,
      StSet_IIIIII: 284,
      StSetStr_IIS: 281,
      StSetStr_IIIS: 282,
      StSetStr_IIIIS: 283,
      StSetStr_IIIIIS: 284,
      StType: 271,
      Tag_SSI__S: 201,
      Tag_SSS__S: 198,
      Tag_S__I: 199,
      Tag_SI__S: 200,
      Tag_S__S: 196,
      Tag_SS__S: 197,
      TagAttach_II: 235,
      TagAttach_IS: 234,
      TagBlockSize: 226,
      TagKeep: 216,
      TagList_S: 246,
      TagList_SI: 247,
      TagList_SII: 248,
      TagList_SIII: 249,
      TagList_SIIII: 250,
      TagList_SIIIII: 251,
      TagList_SIIIIII: 252,
      TagList_SIIIIIII: 253,
      TagList_SIIIIIIII: 254,
      TagStr_SSI__S: 195,
      TagStr_SI__S: 193,
      TagStr_SI__I: 191,
      TagStr_S__I: 190,
      TagStr_SS__S: 192,
      TagStr_S__S: 194,
    },
  } as const satisfies LibraryDef;
  export const V1_10 = {
    name: 'EasyLife',
    version: 'V1_10',
    md5: '938d5915b4eb486b6fa2da6a77e5165b',
    type: 'pro',
    extends: V1_09,
    removed: ['Eltest_get_II__I' ,'Eltest_set_III'],
    routines: {
      Stv_get_IIIII__I: 276,
      Stv_set_IIIIII: 287,
      Stv_get_IIII__I: 275,
      Stv_set_IIIII: 285,
      Stv_get_III__I: 274,
      Stv_set_IIII: 283,
      Stv_get_II__I: 273,
      Stv_set_III: 281,
    },
  } as const satisfies LibraryDef;
  export const V1_44 = {
    name: 'EasyLife',
    version: 'V1_44',
    md5: 'eef3d7fa5da6a0bbb03d8f2a516b93b8',
    type: 'pro',
    extends: V1_10,
    removed: [
      'ElcloseFont', 'ElcloseFonts', 'Elexists', 'ElopenFont', 'ElsetFont',
      'MuiAdd', 'MuiApp', 'MuiApplication', 'MuiBegin', 'MuiDispose', 'MuiDo', 'MuiFlush', //'MuiFn',
      'MuiGet_IS__S', 'MuiGet_II__S', 'MuiGet_IS__I', 'MuiGet_II__I',
      'MuiHook', 'MuiInput', 'MuiMakeButton', 'MuiMakePopbutton', 'MuiNew_SS', 'MuiNew_S', 'MuiNotify_ISIIS', 'MuiNotify_IIIIS',
      'MuiRemove', 'MuiRequest_ISSSS', 'MuiRequest_ISSS', 'MuiSet_ISI', 'MuiSet_III', 'MuiSetStr_ISS', 'MuiSetStr_IIS',
      'StCmp_IIIIIS', 'StCmp_IIIIS', 'StCopy', 'StDup', 'StErase', 'StFree', 'StFreeAll', 'StGet_IIIII__S', 'StGet_IIII__S', 'StGet_IIIII__I', 'StGet_IIII__I',
      'StInput', 'StLen', 'StLoad', 'StLookup', 'StNew', 'StOutput', 'StSave', 'StSet_IIIIII', 'StSet_IIIII', 'StSetStr_IIIIIS', 'StSetStr_IIIIS', 'StType',
      'Stv_get_IIIII__I', 'Stv_set_IIIIII', 'Stv_get_IIII__I', 'Stv_set_IIIII', 'Stv_get_III__I', 'Stv_set_IIII', 'Stv_get_II__I', 'Stv_set_III',
      'Tag_SSI__S', 'Tag_SSS__S', 'Tag_S__I', 'TagAttach_II', 'TagAttach_IS', 'TagBlockSize', 'TagKeep', 'TagList_SIIIIIIII', 'TagList_SIIIIIII',
      'TagStr_SSI__S', 'TagStr_SI__S', 'TagStr_SI__I', 'TagStr_S__I',
      'ElxpkBsave_IISSS',
      'ElxpkBsave_IISS',
      'ElxpkSave_ISSS',
      'ElxpkSave_ISS',
      'StCmp_IIS',
      'StCmp_IIIS',
      'StGet_II__S',
      'StGet_III__S',
      'StGet_II__I',
      'StGet_III__I',
      'StSet_III',
      'StSet_IIII',
      'StSetStr_IIS',
      'StSetStr_IIIS',
      'Tag_SI__S',
      'Tag_S__S',
      'Tag_SS__S',
      'TagList_S',
      'TagList_SI',
      'TagList_SII',
      'TagList_SIII',
      'TagList_SIIII',
      'TagList_SIIIII',
      'TagList_SIIIIII',
      'TagStr_SS__S',
      'TagStr_S__S',
    ],
    routines: {
      EllockFont: 111,
      Elqqzqzqq: 132,
      ElunlockFonts: 112,
      Elzqzqzq: 133,

      ElxpkLoad_SI: 173,
      ElxpkLoad_SSI: 175,
      ElxpkBload_SI: 176,
      ElxpkBload_SSI: 177,
      ElxpkSave_SSI: 168,
      ElxpkSave_SSSI: 179,
      ElxpkBsave_SSII: 169,
      ElxpkBsave_SSSII: 180,
    },
  } as const satisfies LibraryDef;
}

export default EasyLife;
