import type { LibraryDef } from "../types.js";

namespace FD25 {
  export const V1_00 = {
    name: 'FD25',
    version: 'V1_00',
    md5: '8c831d039741f541fe88ba872eebd7aa',
    type: 'pro',
    routines: {
      LvoAccept: 4,
      LvoBind: 2,
      LvoClosesocket: 16,
      LvoConnect: 5,
      LvoDup2socket: 40,
      LvoErrno: 23,
      LvoGetdtablesize: 19,
      LvoGethostbyaddr: 32,
      LvoGethostbyname: 31,
      LvoGethostid: 44,
      LvoGethostname: 43,
      LvoGetnetbyaddr: 34,
      LvoGetnetbyname: 33,
      LvoGetpeername: 14,
      LvoGetprotobyname: 37,
      LvoGetprotobynumber: 38,
      LvoGetservbyname: 35,
      LvoGetservbyport: 36,
      LvoGetsocketevents: 46,
      LvoGetsockname: 13,
      LvoGetsockopt: 12,
      LvoInetAddr: 26,
      LvoInetLnaof: 27,
      LvoInetMakeaddr: 29,
      LvoInetNetof: 28,
      LvoInetNetwork: 30,
      LvoInetNtoA: 25,
      LvoIoctlsocket: 15,
      LvoListen: 3,
      LvoObtainsocket: 20,
      LvoRecv: 9,
      LvoRecvfrom: 8,
      LvoRecvmsg: 42,
      LvoReleasecopyofsocket: 22,
      LvoReleasesocket: 21,
      LvoSend: 7,
      LvoSendmsg: 41,
      LvoSendto: 6,
      LvoSeterrnoptr: 24,
      LvoSetsocketsignals: 18,
      LvoSetsockopt: 11,
      LvoShutdown: 10,
      LvoSocket: 1,
      LvoSocketbasetaglist: 45,
      LvoVsyslog: 39,
      LvoWaitselect: 17,
    },
  } as const satisfies LibraryDef;
}

export default FD25;
