import type { LibraryDef } from "../types.js";

namespace Int {
  export const V1_00 = {
    md5: 'fe9976e530c4e014afe97e7d1d93435d',
    type: 'pro',
    routines: {
      WbActivateGt: 70,
      WbAslDir: 72,
      WbAslInfo: 59,
      WbAslPattern: 58,
      WbAslReq: 21,
      WbBackPen: 25,
      WbBoolGadget: 61,
      WbBox: 75,
      WbClearKey: 31,
      WbCloseScreen: 41,
      WbCloseWindow: 3,
      WbCurrentWindow: 81,
      WbDefault: 39,
      WbDraw: 22,
      WbDrawMode: 73,
      WbDtImageToScreen: 83,
      WbEllipse: 26,
      WbEvent: 28,
      WbFile: 35,
      WbFillBox: 27,
      WbFindString: 71,
      WbFlashScreen: 8,
      WbFrontPen: 24,
      WbGetIffPalette: 82,
      WbGtGadget: 63,
      WbGtString: 67,
      WbIffToBank: 49,
      WbImageToWindow: 50,
      WbIntuitext: 54,
      WbItem: 16,
      WbJoy: 53,
      WbKeycode: 30,
      WbLoadRgb: 47,
      WbMenu: 15,
      WbMenuItem: 12,
      WbMenuOn: 13,
      WbMenuSubItem: 14,
      WbMenuTitle: 10,
      WbMouseKey: 74,
      WbMousex: 17,
      WbMousey: 18,
      WbMoveScreen: 87,
      WbMoveWindow: 7,
      WbOpenScreen: 40,
      WbOpenWindow: 2,
      WbPalette: 45,
      WbPasteIcon: 76,
      WbPutChr: 69,
      WbSaveIff: 89,
      WbScreenBase: 85,
      WbScreenFlags: 42,
      WbScreenNum: 43,
      WbScreenOffset: 86,
      WbScroll: 51,
      WbSetGtString: 68,
      WbSubItem: 80,
      WbText: 19,
      WbTitles: 23,
      WbWindowBase: 48,
      WbWindowFlags: 9,
      WbWindowIds: 29,
      WbWindowNum: 20,
    },
  } as const satisfies LibraryDef;
}

export default Int;
