import type { LibraryDef } from "../types.js";

export namespace JDColour {
  export const V2_00 = {
    name: 'JDColour',
    version: 'V2_00',
    md5: '264eda324a9da65718db49511df98206',
    type: 'pro',
    routines: {
      JdAntiqueColour: 9,
      JdBlueValue: 16,
      JdBswap: 63,
      JdChangeColours: 39,
      JdCloseCon: 75,
      JdComplementColour: 13,
      JdCopyColour: 27,
      JdCutOff: 56,
      JdDarkestColour: 53,
      JdDrive: 79,
      JdFalseColour: 10,
      JdFile: 60,
      JdFillColour: 40,
      JdFit: 55,
      JdGreenValue: 15,
      JdGreyColour: 8,
      JdGuru: 38,
      JdInputCon: 77,
      JdKeyToAsc: 78,
      JdLightestColour: 52,
      JdLoadPalette: 37,
      JdLswap: 65,
      JdMixColours: 11,
      JdMouse: 48,
      JdNegativeColour: 12,
      JdOpenCon: 74,
      JdPath: 61,
      JdPrintCon: 76,
      JdPseudoPalette: 25,
      JdRedValue: 14,
      JdRequest_SSSSSSS: 66,
      JdRequest_SSSSSS: 67,
      JdRequest_SSSSS: 68,
      JdRequest_SSSS: 69,
      JdRequest_SSS: 70,
      JdRgbValue: 24,
      JdRprint: 54,
      JdSavePalette: 36,
      JdScreenBorder: 58,
      JdScreenConvert: 33,
      JdSeparateBlack: 17,
      JdSeparateBlue: 21,
      JdSeparateCyan: 23,
      JdSeparateGreen: 20,
      JdSeparateMagenta: 22,
      JdSeparateRed: 19,
      JdSeparateYellow: 18,
      JdSetoutputAmiga: 49,
      JdSetoutputAmos: 50,
      JdSlideDown: 46,
      JdSlideLeft: 43,
      JdSlideRight: 44,
      JdSlideUp: 45,
      JdSlideX: 41,
      JdSlideY: 42,
      JdSpreadPalette: 7,
      JdSwapColours: 26,
      JdToneColour: 28,
      JdWaitRaster: 59,
      JdWswap: 64,
    },
  } as const satisfies LibraryDef;
}

export namespace JDInt {
  export const V1_30 = {
    name: 'JDInt',
    version: 'V1_30',
    md5: 'af1fc552355df46ea40e5b7eaa7c3664',
    type: 'pro',
    routines: {
      JdCloseIntscreen: 6,
      JdCloseIntwindow: 4,
      JdIntbar: 14,
      JdIntbox: 23,
      JdIntclass: 17,
      JdIntcls: 27,
      JdIntcls_I: 37,
      JdIntcolour: 18,
      JdIntcursX: 19,
      JdIntcursY: 20,
      JdIntdrawmode: 13,
      JdIntellipse: 25,
      JdIntevent: 10,
      JdIntfill: 26,
      JdIntline: 24,
      JdIntlocate: 7,
      JdIntmouseX: 15,
      JdIntmouseY: 16,
      JdIntmove: 38,
      JdIntpaper: 12,
      JdIntpen: 11,
      JdIntplot: 29,
      JdIntpoint: 28,
      JdIntprint: 8,
      JdIntscreenHeight: 40,
      JdIntscreenWidth: 39,
      JdIntzone: 21,
      JdOpenIntscreen: 5,
      JdOpenIntwindow: 3,
      JdRemIntzones: 22,
      JdShowIntscreen: 35,
      JdShowIntwindow: 36,
      JdUseIntscreen: 33,
      JdUseIntwindow: 34,
    },
  } as const satisfies LibraryDef;
}

export namespace JDK {
  export const V1_10 = {
    name: 'JDK',
    version: 'V1_10',
    md5: 'efaa5ad764b8a2d8cc4a652bbd4b3cea',
    type: 'pro',
    routines: {
      JdMatch: 7,
      JdMatchNocase: 8,
      JdRelabel: 6,
      JdStarJokerOff: 12,
      JdStarJokerOn: 11,
      JdToggleClick: 13,
    },
  } as const satisfies LibraryDef;
}

export namespace JD {
  export const V4_60 = {
    name: 'JD',
    version: 'V4_60',
    md5: '0bceea592c953dc64ccd7fe0bece7733',
    type: 'pro',
    routines: {
      JdActualDate: 65,
      JdActualTime: 66,
      JdArcus: 129,
      JdAreaFirst: 23,
      JdAreaLast: 24,
      JdArraySClear_I: 152,
      JdArrayClear_I: 153,
      JdArraySwap: 151,
      JdAsl: 76,
      JdAsr: 77,
      JdBootchecksum: 57,
      JdChange: 13,
      JdCharX: 94,
      JdCharY: 95,
      JdCheckprt: 83,
      JdChecksum: 56,
      JdCompare: 3,
      JdCopy: 107,
      JdCount: 8,
      JdCountDirs: 136,
      JdCountFiles: 137,
      JdCrypt: 16,
      JdCut: 39,
      JdDate: 7,
      JdDeoct: 62,
      JdDetab: 139,
      JdDiskchange: 42,
      JdDistance: 127,
      JdDledOff: 146,
      JdDledOn: 147,
      JdDoubleClick: 145,
      JdDrawAngle: 68,
      JdDrawSegment: 154,
      JdDump: 55,
      JdE__F: 86,
      JdEncrypt: 17,
      JdEqv: 79,
      JdExtend: 18,
      JdExval_IIS: 19,
      JdExval_II: 20,
      JdFileComment: 123,
      JdFileProtection: 122,
      JdFileSize: 117,
      JdFileType: 118,
      JdFirstup: 14,
      JdFlush: 134,
      JdFormat: 106,
      JdGetArea: 21,
      JdGetNumber: 37,
      JdGetString: 44,
      JdGetTab: 140,
      JdHardware: 90,
      JdHexdump: 63,
      JdImp: 78,
      JdInsert: 40,
      JdInstall: 105,
      JdIntscreenBase: 80,
      JdIntwindowBase: 81,
      JdKeypress: 69,
      JdKeywait: 26,
      JdLargestChipFree: 114,
      JdLargestFastFree: 115,
      JdLimit: 10,
      JdLinstr: 82,
      JdLogical: 92,
      JdLsl: 74,
      JdLsr: 75,
      JdMoffClick: 141,
      JdMoffKey: 142,
      JdMultiOff: 143,
      JdMultiOn: 144,
      JdMwait: 25,
      JdOct_I: 59,
      JdOct_II: 60,
      JdOdd: 58,
      JdPaste: 9,
      JdPercent: 61,
      JdPi__F: 128,
      JdPpdecrunch: 120,
      JdPpfindMem: 119,
      JdPrint: 89,
      JdPrivate: 2,
      JdRastport: 38,
      JdReadSector: 50,
      JdReduceDim: 148,
      JdRelabel: 109,
      JdReset: 67,
      JdResetArea: 22,
      JdResetDim: 149,
      JdRol_S__S: 49,
      JdRol_II__I: 70,
      JdRor_S__S: 48,
      JdRor_II__I: 71,
      JdRoxl: 72,
      JdRoxr: 73,
      JdScreenPlanes: 11,
      JdScreenResolution__I: 12,
      JdSecstime: 131,
      JdSetclock: 4,
      JdSetComment: 126,
      JdSetdate: 5,
      JdSetProtection: 125,
      JdShortformat: 110,
      JdSkip: 15,
      JdSlideDown: 104,
      JdSlideLeft: 100,
      JdSlideRight: 101,
      JdSlideUp: 103,
      JdSlideX: 98,
      JdSlideY: 99,
      JdSpline: 84,
      JdSpread: 46,
      JdSquash: 111,
      JdStream: 121,
      JdTextfont: 88,
      JdTime: 6,
      JdTimesecs: 130,
      JdTscroll: 47,
      JdType: 64,
      JdVideoOff: 113,
      JdVideoOn: 112,
      JdVolume: 91,
      JdWaitAmiga: 43,
      JdWaitEvent: 45,
      JdWriteSector: 51,
      JdXPos: 132,
      JdYPos: 133,
    },
  } as const satisfies LibraryDef;
  export const V5_30 = {
    name: 'JD',
    version: 'V5_30',
    md5: 'c5ce74be26b1236a98307381e6f1758a',
    type: 'pro',
    extends: V4_60,
    removed: [
      'JdIntscreenBase',
      'JdIntwindowBase',
      'JdSlideDown',
      'JdSlideLeft',
      'JdSlideRight',
      'JdSlideUp',
      'JdSlideX',
      'JdSlideY',
      'JdStream',
    ],
    routines: {
      JdDay_III__I: 98,
      JdDay_I__S: 99,
      JdDayOfYear: 97,
      JdDayval: 103,
      JdE__I: 86,
      JdExdatazone: 121,
      JdFind_IS: 80,
      JdFind_ISI: 81,
      JdGetDim: 154,
      JdGrid: 157,
      JdLeapYear: 96,
      JdMonthval: 104,
      JdNinstr_SS: 155,
      JdNinstr_SSI: 156,
      JdPi__I: 128,
      JdScreenResolution__V: 161,
      JdXoffset: 158,
      JdYearval: 102,
      JdYoffset: 159,
    },
  } as const satisfies LibraryDef;
  export const V5_90 = {
    name: 'JD',
    version: 'V5_90',
    md5: '0f43a4c5583d2ecb04bc8aacf7194d25',
    type: 'pro',
    extends: V5_30,
    removed: [
      'JdCompare',
      'JdScreenResolution__I',
    ],
    routines: {
      JdChipset: 164,
      JdCpu: 162,
      JdDpath: 160,
      JdFpu: 163,
      JdPattern: 3,
    },
  } as const satisfies LibraryDef;
}

export namespace Prt {
  export const V1_10 = {
    name: 'Prt',
    version: 'V1_10',
    md5: '82dc8261522d3b49e664b786d4b007aa',
    type: 'pro',
    routines: {
      PrtBold: 10,
      PrtBoldOff: 11,
      PrtCenter: 44,
      PrtClrHtab: 57,
      PrtClrHtabs: 58,
      PrtClrMargins: 54,
      PrtClrVtab: 59,
      PrtClrVtabs: 60,
      PrtDouble: 20,
      PrtDoubleOff: 21,
      PrtElite: 12,
      PrtEliteOff: 13,
      PrtEnlarged: 16,
      PrtEnlargedOff: 17,
      PrtFine: 14,
      PrtFineOff: 15,
      PrtFjustify: 43,
      PrtInit: 5,
      PrtItalics: 6,
      PrtItalicsOff: 7,
      PrtJustifyOff: 47,
      PrtLjustify: 41,
      PrtLspaceEight: 45,
      PrtLspaceSix: 46,
      PrtNlq: 22,
      PrtNlqOff: 23,
      PrtPlineDown: 49,
      PrtPlineUp: 48,
      PrtProp: 39,
      PrtPropOff: 40,
      PrtReset: 4,
      PrtRjustiy: 42,
      PrtSetBmargin: 53,
      PrtSetDanishi: 32,
      PrtSetDanishii: 38,
      PrtSetDefTabs: 61,
      PrtSetFrench: 29,
      PrtSetGerman: 30,
      PrtSetHtab: 55,
      PrtSetItalian: 34,
      PrtSetJapanese: 36,
      PrtSetLmargin: 50,
      PrtSetNorge: 37,
      PrtSetRmargin: 51,
      PrtSetSpanish: 35,
      PrtSetSweden: 33,
      PrtSetTmargin: 52,
      PrtSetUk: 31,
      PrtSetUs: 28,
      PrtSetVtab: 56,
      PrtShadow: 18,
      PrtShadowOff: 19,
      PrtSub: 26,
      PrtSubOff: 27,
      PrtSuper: 24,
      PrtSuperOff: 25,
      PrtUnder: 8,
      PrtUnderOff: 9,
    },
  } as const satisfies LibraryDef;
  export const V1_40 = {
    name: 'Prt',
    version: 'V1_40',
    md5: '1008c1ef6ab47c7309e79c63e042dd4b',
    type: 'pro',
    routines: {
      JdPrtAspect: 65,
      JdPrtBold: 10,
      JdPrtBoldOff: 11,
      JdPrtBordersOff: 74,
      JdPrtCenter: 44,
      JdPrtClrHtab: 57,
      JdPrtClrHtabs: 58,
      JdPrtClrMargins: 54,
      JdPrtClrVtab: 59,
      JdPrtClrVtabs: 60,
      JdPrtDensity: 68,
      JdPrtDouble: 20,
      JdPrtDoubleOff: 21,
      JdPrtDoubleunder: 72,
      JdPrtDoubleunderOff: 73,
      JdPrtElite: 12,
      JdPrtEliteOff: 13,
      JdPrtEnlarged: 16,
      JdPrtEnlargedOff: 17,
      JdPrtFf: 75,
      JdPrtFine: 14,
      JdPrtFineOff: 15,
      JdPrtFjustify: 43,
      JdPrtImage: 66,
      JdPrtInit: 5,
      JdPrtItalics: 6,
      JdPrtItalicsOff: 7,
      JdPrtJustifyOff: 47,
      JdPrtLf: 70,
      JdPrtLjustify: 41,
      JdPrtLspaceEight: 45,
      JdPrtLspaceSix: 46,
      JdPrtNlq: 22,
      JdPrtNlqOff: 23,
      JdPrtPlineDown: 49,
      JdPrtPlineUp: 48,
      JdPrtProp: 39,
      JdPrtPropOff: 40,
      JdPrtReset: 4,
      JdPrtReverseLf: 71,
      JdPrtRjustiy: 42,
      JdPrtSetBmargin: 53,
      JdPrtSetDanishi: 32,
      JdPrtSetDanishii: 38,
      JdPrtSetDefTabs: 61,
      JdPrtSetFrench: 29,
      JdPrtSetGerman: 30,
      JdPrtSetHtab: 55,
      JdPrtSetItalian: 34,
      JdPrtSetJapanese: 36,
      JdPrtSetLmargin: 50,
      JdPrtSetNorge: 37,
      JdPrtSetRmargin: 51,
      JdPrtSetSpanish: 35,
      JdPrtSetSweden: 33,
      JdPrtSetTmargin: 52,
      JdPrtSetUk: 31,
      JdPrtSetUs: 28,
      JdPrtSetVtab: 56,
      JdPrtShade: 64,
      JdPrtShadow: 18,
      JdPrtShadowOff: 19,
      JdPrtSub: 26,
      JdPrtSubOff: 27,
      JdPrtSuper: 24,
      JdPrtSuperOff: 25,
      JdPrtThreshold: 67,
      JdPrtUnder: 8,
      JdPrtUnderOff: 9,
    },
  } as const satisfies LibraryDef;
}
