import type { LibraryDef } from "../types.js";

namespace PowerBobs {
  export const BETA6 = {
    name: 'PowerBobs',
    version: 'BETA6',
    md5: '3f2760e9aada02aa8807d88cb42b764c',
    type: 'pro',
    routines: {
      ConvertSprites: 28,
      IPbob: 5,
      Pbob_IIIII: 15,
      Pbob_IIII: 2,
      PbobClear: 8,
      PbobDbuf: 12,
      PbobDraw: 9,
      PbobErase: 10,
      PbobFastcol_II: 16,
      PbobFastcol_III: 17,
      PbobHeight: 7,
      PbobOff: 3,
      PbobOff_I: 4,
      PbobOff_II: 21,
      PbobspriteFastcol_II: 20,
      PbobspriteFastcol_III: 19,
      PbobUpdate: 22,
      PchannelToPbob: 40,
      Pdraw25fps: 38,
      PfastCol: 18,
      Psprite: 30,
      PspriteErase: 29,
      PspriteMax: 35,
      PspriteOff: 32,
      PspriteOff_I: 31,
      PspriteOff_II: 33,
      PspriteUpdate: 34,
      PswapClear: 39,
      PsyncEvery: 42,
      PsyncPbob: 41,
      ReservePbobs: 6,
      SetPbob: 23,
      XPbob: 13,
      XPsprite: 36,
      XscrMouse: 24,
      XscrSprite: 26,
      YPbob: 14,
      YPsprite: 37,
      YscrMouse: 25,
      YscrSprite: 27,
    },
  } as const satisfies LibraryDef;
  export const V1_00 = {
    name: 'PowerBobs',
    version: 'V1_00',
    md5: '9503250d59a08c2fe564388ffa18361c',
    type: 'pro',
    extends: BETA6,
    removed: ['PfastCol', 'Psprite'],
    routines: {
      Padd: 70,
      Pasl: 75,
      Pasr: 76,
      PchannelToPsprite: 44,
      Pdebug: 116,
      Pdec: 71,
      Pdiv: 77,
      Pdraw25fps_I: 38,
      PfastBobcol: 18,
      PfastBobsprcol: 50,
      PfastSprbobcol: 57,
      PfastSprcol: 54,
      Pinc: 72,
      Plsl: 73,
      Plsr: 74,
      Pmul: 62,
      PmulShift: 63,
      Psprite_IIIII: 51,
      Psprite_IIII: 30,
      PspritebobFastcol_II: 56,
      PspritebobFastcol_III: 55,
      PspriteFastcol_II: 52,
      PspriteFastcol_III: 53,
      Psum: 69,
      PsyncEveryPbob: 49,
      PsyncEveryPsprite: 48,
      PsyncPsprite: 45,
      Same: 68,
      Set68020Amal: 47,
      SetFastpbobMode: 46,
      SetPdecRange: 65,
      SetPincRange: 66,
      SetPspriteColours: 43,
      SetPsumRange: 64,
      UnsetPaddRange: 60,
      UnsetPdecRange: 58,
      UnsetPincRange: 59,
      UnsetPsumRange: 61,
    },
  } as const satisfies LibraryDef;
}

export default PowerBobs;
