import type { LibraryDef } from "../types.js";

namespace SLN {
  export const V2_00 = {
    name: 'SLN',
    version: 'V2_00',
    md5: 'ad05eb48960430d9ffe48f82135ff51c',
    type: 'pro',
    routines: {
      SAbase: 13,
      SAclear: 30,
      SAerase: 33,
      SAeraseAll: 34,
      SAinit_IIIII: 11,
      SAinit_IIIIII: 31,
      SArray_IIII: 14,
      SArray_III: 22,
      SArray_II: 23,
      SAset_IIIII: 19,
      SAset_IIII: 20,
      SAset_III: 21,
      SAsize: 12,
      SAtype: 18,
      SAxsize: 15,
      SAysize: 16,
      SAzsize: 17,
      SChecksum: 83,
      SCompare: 35,
      SDelete: 95,
      SDiskAbort: 79,
      SDiskChanges: 76,
      SDiskClose: 65,
      SDiskDevCheck: 78,
      SDiskOpen: 64,
      SDiskProtState: 75,
      SDiskRead: 68,
      SDiskRename: 84,
      SDiskSendRead: 69,
      SDiskSendWrite: 72,
      SDiskState: 74,
      SDiskUpdate: 82,
      SDiskWait: 80,
      SDiskWrite: 71,
      SIadr: 25,
      SIbase: 24,
      SIconify: 63,
      SIerase: 29,
      SIfree: 27,
      SIinit: 26,
      //SMask: -1,
      SMotorOff: 67,
      SMotorOn: 66,
      SMouseButton: 5,
      SMouseOff: 2,
      SMouseOn: 1,
      SNumTracks: 77,
      SSamBank__I: 55,
      SSamBank_I__V: 43,
      SSamBankErase_I: 45,
      SSamBankErase: 59,
      SSamBankLoad_SI: 47,
      SSamBankLoad_S: 46,
      SSamBankReserve: 53,
      SSamBankReserve_I: 44,
      SSamBankSave_S: 48,
      SSamBankSave_SI: 49,
      SSamBase: 50,
      SSamChipLoad_S: 61,
      SSamChipLoad_SI: 62,
      SSamClip: 51,
      SSamDel: 42,
      SSamFreq: 56,
      SSamLength: 60,
      SSamLoad_S: 38,
      SSamLoad_SI: 39,
      SSamPlay: 40,
      SSamStop: 58,
      SSetFreq: 41,
      STrackLength: 92,
      STrackLoad_S: 88,
      STrackLoad_SI: 89,
      STrackPlay_I: 96,
      STrackPlay_II: 86,
      STrackPlay_III: 87,
      STrackStop: 90,
      STrackTempo_I__V: 93,
      STrackTempo__I: 94,
      STrackVolume: 91,
      SVolume: 37,
      SXMouse__I: 3,
      SXMouse_I__V: 7,
      SYMouse__I: 4,
      SYMouse_I__V: 8,
    },
  } as const satisfies LibraryDef;
}

export default SLN;
