import type { LibraryDef } from "../types.js";

namespace TOME {
  export const V3_10 = {
    name: 'TOME',
    version: 'V3_10',
    type: 'creator',
    md5: 'c4ec3d18c54963a44e4be8fb92387dd2',
    routines: {
      BrikBank: 12,
      Briks: 25,
      BrikX: 5,
      BrikY: 6,
      MapBank: 11,
      MapBase: 28,
      MapBottom: 19,
      MapBrik: 23,
      MapCheck: 31,
      MapDo: 15,
      MapFx: 34,
      MapFy: 35,
      MapHx: 32,
      MapHy: 33,
      MapLeft: 16,
      MapPlot: 20,
      MapRight: 17,
      MapScanX: 8,
      MapScanY: 9,
      MapTile: 4,
      MapTop: 18,
      MapView: 14,
      MapX: 21,
      MapY: 22,
      PasteBrik: 24,
      TileSize: 10,
      TileVal: 7,
      TileValBank: 13,
      TinyBank: 30,
      TinyMap: 29,
      TmeCredit: 26,
      TmeVer: 27,
      Xtile: 3,
      Ytile: 2,
    },
  } as const satisfies LibraryDef;
  export const V4_23 = {
    name: 'TOME',
    version: 'V4_23',
    type: 'creator',
    md5: '3220a6ac580d6949f6ddc163cdb34a0c',
    extends: V3_10,
    renamed: {
      TileValBank: 'TileTypBank',
    },
    routines: {
      ListTile: 41,
      MapAbLength: 49,
      MapAnAt: 55,
      MapAnFreeze: 52,
      MapAnim: 44,
      MapAnimBank: 46,
      MapAnimOff: 43,
      MapAnimOn: 42,
      MapAnMove: 56,
      MapAnPoint: 54,
      MapAnUnfreeze: 53,
      MapFall: 50,
      MapHandle: 47,
      MapHandleInit: 48,
      MapLength: 39,
      MapPaste: 36,
      MapPosX: 63,
      MapPosY: 64,
      MapSetZone: 75,
      MapSwapTile: 51,
      MapUpdate: 40,
      MapUpdateOff: 38,
      MapUpdateOn: 37,
      MapZbLength: 73,
      MapZone: 76,
      MapZoneBank: 74,
      TileCount: 65,
      TileTag: 60,
      TileTagSet: 59,
      TileTagsOff: 58,
      TileTagsOn: 57,
      TileTagX: 61,
      TileTagY: 62,
      TileTypBank: 13,
    },
  } as const satisfies LibraryDef;
}

export default TOME;
